spring:
  shardingsphere:
    datasource:
      names: ds
      ds:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123123
    rules:
      sharding:
        sharding-algorithms:
          im_message-inline:
            type: INLINE
            props:
              algorithm-expression: im_message$->{to_user_id % 3}
        broadcast-tables: im_business_type
        tables:
          im_message:
            actual-data-nodes: ds.im_message$->{0..2}
            table-strategy:
              standard:
                sharding-column: to_user_id
                sharding-algorithm-name: im_message-inline
            key-generator-strategy:
              column: id
              key-generator-name: snowflake
        key-generators:
          snowflake:
            type: SNOWFLAKE
    props:
      sql-show: true

