spring:
  shardingsphere:
    datasource:
      names: ds2,ds3
      ds2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds2?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123123
      ds3:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ds3?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123123
    rules:
      sharding:
        default-database-strategy:
          standard:
            sharding-column: from_user_id
            sharding-algorithm-name: database-inline
        broadcast-tables: im_business_type
        sharding-algorithms:
          database-inline:
            type: INLINE
            props:
              algorithm-expression: ds$->{from_user_id % 2 + 2}
          im_message-inline:
            type: INLINE
            props:
              algorithm-expression: im_message$->{to_user_id % 3}
        tables:
          im_message:
            actual-data-nodes: ds$->{2..3}.im_message$->{0..2}
            table-strategy:
              standard:
                sharding-column: to_user_id
                sharding-algorithm-name: im_message-inline
            key-generator-strategy:
              column: id
              key-generator-name: snowflake
        key-generators:
          snowflake:
            type: SNOWFLAKE
    props:
      sql-show: true

