server:
  port: 8003

spring:
  application:
    name: integration-service
  profiles:
    active: @spring.profiles.active@
  cloud:
    nacos:
      server-addr: @spring.cloud.nacos.discovery.server-addr@
      enabled: true
    config:
      server-addr: http://nacos.xumingyu.com/